name: docker-sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  docker-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Cache finish images
      uses: actions/cache@v4
      with:
        path: finish.images
        key: finish-images-${{ github.run_number }}
        restore-keys: |
          finish-images-
    - name: Sync images
      env:
        ALIYUN_REGISTRY_USER: ${{ secrets.ALIYUN_REGISTRY_USER }}
        ALIYUN_REGISTRY_PASSWORD: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
        ALIYUN_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}
        ALIYUN_NAME_SPACE: ${{ secrets.ALIYUN_NAME_SPACE }}
      uses: qibao07/skopeo-action@main
      with:
        cmd: chmod +x ./start.sh && ./start.sh
