name: docker-sync

on:
  workflow_dispatch:

jobs:
  docker-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up skopeo
      uses: warjiang/setup-skopeo@latest
      with:
        version: latest
    - name: Sync images
      run: |
        chmod +x ./start.sh
        ./start.sh